In [16]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data1 = pd.read_csv('FoodPrice_in_Turkey.csv',header=0)
data1

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

## mã hóa dữ liệu productname với one -hot encoder sử dụng scikit learn

In [18]:
en1 = OneHotEncoder(sparse=False)
encoded1 = en1.fit_transform(data1.loc[:,['ProductName']])
encoded1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
aaa =np.array(data1.loc[:,'ProdcutName'])
aaa

KeyError: 'ProdcutName'

In [20]:
# mã hóa productName sử dụng pandas

pd.get_dummies(data1.loc[:,'ProductName'])

,Apples (red) - Retail,Apples - Retail,Bananas - Retail,Beans (white) - Retail,Bread (common) - Retail,Bread (pita) - Retail,Bulgur - Retail,Cabbage - Retail,Cauliflower - Retail,Cheese - Retail,...,Tea (herbal) - Retail,Tea - Retail,Tomatoes (paste) - Retail,Tomatoes - Retail,Transport (public) - Retail,"Wage (non-qualified labour, non-agricultural) - Retail",Water - Retail,Wheat flour - Retail,Yogurt - Retail,Zucchini - Retail
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7377,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7378,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7379,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7380,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder() #Đặt object
lb = encoder.fit_transform(data1.loc[:,'ProductName']) #Dùng cho dữ liệu 1 chiều
print(lb)

[37 37 37 ... 11 11 11]

In [23]:
data1.loc[:,'ProductName'].astype('category').cat.codes

0       37
1       37
2       37
3       37
4       37
        ..
7376    11
7377    11
7378    11
7379    11
7380    11
Length: 7381, dtype: int8

In [25]:
ccc = pd.cut(data1.loc[:,'Price'],5)#5 khoang3
ccc

0       (0.0947, 32.092]
1       (0.0947, 32.092]
2       (0.0947, 32.092]
3       (0.0947, 32.092]
4       (0.0947, 32.092]
              ...
7376    (32.092, 63.931]
7377    (32.092, 63.931]
7378    (32.092, 63.931]
7379    (32.092, 63.931]
7380    (32.092, 63.931]
Name: Price, Length: 7381, dtype: category
Categories (5, interval[float64, right]): [(0.0947, 32.092] < (32.092, 63.931] < (63.931, 95.769] < (95.769, 127.607] < (127.607, 159.446]]

In [26]:
ccc.value_counts()

(0.0947, 32.092]      6223
(32.092, 63.931]       867
(63.931, 95.769]       155
(95.769, 127.607]      105
(127.607, 159.446]      31
Name: Price, dtype: int64

In [27]:
pd.value_counts(ccc)

(0.0947, 32.092]      6223
(32.092, 63.931]       867
(63.931, 95.769]       155
(95.769, 127.607]      105
(127.607, 159.446]      31
Name: Price, dtype: int64